#spring:
#  application:
#    name: spider4j
#  datasource:
#    url: jdbc:mysql://101.132.229.69:3306/spingboot?useUnicode=true&useSSL=false&characterEncoding=utf-8
#   data-username: root
#   data-password: Xzcd1993
server:
  port: 8089
spring:
  application:
    name: spider4j
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://101.132.229.69:3306/springboot?useUnicode=true&useSSL=false&characterEncoding=utf-8
    username: root
    password: Xzcd1993
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
     # 初始化大小，最小，最大
      initial-size: 5
      minIdle : 5
      max-active: 10
      # 配置获取连接等待超时的时间
      maxWait : 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000

      validation-query:  SELECT 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
       # 打开PSCache，并且指定每个连接上PSCache的大小
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
       # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙

      filter-class-names: stat,wall,slf4j
       # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
       # 合并多个DruidDataSource的监控数据
      use-global-data-source-stat: true

  data:
    mongodb:
      uri: mongodb://101.200.44.47:27017
      database: springboot
mybatis:
  type-aliases-package: com.xu.spider4j.entity

#测试数据
myconfig:
  testId: 123
  testName: charlie